DROP TABLE IF EXISTS t_user;
CREATE TABLE `t_user` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    mail VARCHAR(250) NOT NULL,
    pass VARCHAR(250) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_general_ci;